config/routes.rb
Rails.application.routes.draw do
  get 'maintanence_service/index'

  get 'maintanence_service/new'

  post '/tenants/maintanence_services' => "maintanence_service#create"

  get 'maintanence_service/show'

  get 'workspace/index'

  root "sessions/sessions#index"
  namespace :sessions do
     resources :sessions
  end

  get "users" => "users#new", :as => "users"
  get "new_user_sign_up" => "users#new", :as => "new_user_sign_up"
  get "user_logged_out" => "sessions/sessions#destroy", :as => "user_logged_out"
  get "property_owners/PropertyOwner" => "property_owners#show", :as => "property_owner_workspace"
  get "tenants/Tenant" => "tenants#show", :as => "tenant_workspace"
  post "get_city" => "tenants#get_city"
  post "get_apts" => "tenants#get_apts"
  post "get_units" => "tenants#get_units"
  post "associate_tenant" => "tenants#associate_tenant"

  resources :properties
  resources :users
  resources :property_owners, controller: 'users', user_designation: 'PropertyOwner'
  resources :tenants, controller: 'users', user_designation: 'Tenant'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/workspace.rb
module Workspace
  def self.table_name_prefix
    'workspace_'
  end
end

app/models/workspace/property_owner.rb
class Workspace::PropertyOwner < ApplicationRecord
  belongs_to :user
end

app/models/workspace/tenant_workspace.rb
class Workspace::TenantWorkspace < ApplicationRecord
end

app/controllers/workspaces/workspace_controller.rb
class WorkspaceController < ApplicationController
  def index
  end
  
  def show
    @tenant = Tenant.find(session[:user_id])
  end
end

app/helpers/workspace_helper.rb
module WorkspaceHelper
end

app/views/workspace/_show_maintenance_req.html.erb
<h1>I need maintanence!</h1>
<%= form_for @maintanence_service, url: tenants_maintanence_services_path do |ms| %>	
	<p>
        <%= ms.label :location %><br />
        <%= ms.text_field :location, :class => 'form-control' %>
      </p>
      <p>
        <%= ms.label :maintanence_type %><br />
        <%= ms.text_field :maintanence_type, class: 'form-control' %>
      </p>
      <p>
        <%= ms.label :desc, "Description" %><br />
        <%= ms.text_field :desc, class: 'form-control' %>
      </p>
      <p>
        <%= ms.label :time %>
        <%= ms.text_field :time, {:class => 'form-control'} %>
      </p>
       <p>
        <%= ms.label :emergency, "Emergency" %>
        <%= ms.check_box :emergency, {:class => 'form-control'} %>
      </p>
     <p class="button"><%= ms.submit "Create Service Request", :class => 'btn btn-default' %></p>
<% end %>

app/views/workspace/_show_property_owner_workspace.html.erb
<style>
	.left-content
	{
		float: left;
		height: 300px;
		width: 75%;
		background-color: #eff5f5;
	}
	
	.right-content
	{
		float: right;
		height: 300px;
		width: 25%;
	}
	
	.boxes
	{
		float: left;
		width: 125px;
		height: 125px;
		background-color: #eff5f5;
		margin: 5px;
	}
</style>
<% @properties.each do |property| %>
<div class="primary panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">
			<%= property.title %>
		</h3>
	</div>
	<div class="panel-body">
		<div class="left-content">
			
		</div>
		<div class="right-content">
			<div class="boxes"></div>
			<div class="boxes"></div>
			<div class="boxes"></div>
			<div class="boxes"></div>
		</div>
		<div style="clear: both;"></div>
	</div>
</div>
<% end %>

app/views/workspace/_show_tenant_workspace.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">
		<h1 class="panel-title" style="float:left">
			Monthly report for Unit# <%#= @unit.address2 %>
		</h1>
			<button class="btn btn-primary" type="button" style="float:right">
				  Rent is due in: <span class="badge"><%= Unit.due_date%></span>
			</button>
		<div style="clear:both"></div>
	</div>
	<div class="panel-body">
		<fieldset><legend>Charges Incurred</legend>
			<table class="table table-bordered">
				<thead class="thead thead-inverse">
					<tr>
						<th>Item</th>
						<th>Amount</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Parking</td><td>12.95</td>
					</tr>
					<tr>
						<td>Landscaping</td><td>7.55</td>
					</tr>
					<tr>
						<td>Gym Maintanance</td><td>4.95</td>
					</tr>
					<tr>
						<td>Pool Maintenance</td><td>3.23</td>
					</tr>
				</tbody>
				<tfoot>
					<tr>
						<td>Total</td><td>1255.00</td>
					</tr>
				</tfoot>
			</table>
	</fieldset>
	</div>

</div>

app/views/workspace/index.html.erb
<h1>Workspace#index</h1>
<p>Find me in app/views/workspace/index.html.erb</p>

app/views/workspace/show.html.erb
<h1>Hello Workspace</h1>