config/routes.rb
Rails.application.routes.draw do
  get 'maintanence_service/index'

  get 'maintanence_service/new'

  post '/tenants/maintanence_services' => "maintanence_service#create"

  get 'maintanence_service/show'

  get 'workspace/index'

  root "sessions/sessions#index"
  namespace :sessions do
     resources :sessions
  end

  get "users" => "users#new", :as => "users"
  get "new_user_sign_up" => "users#new", :as => "new_user_sign_up"
  get "user_logged_out" => "sessions/sessions#destroy", :as => "user_logged_out"
  get "property_owners/PropertyOwner" => "property_owners#show", :as => "property_owner_workspace"
  get "tenants/Tenant" => "tenants#show", :as => "tenant_workspace"
  post "get_city" => "tenants#get_city"
  post "get_apts" => "tenants#get_apts"
  post "get_units" => "tenants#get_units"
  post "associate_tenant" => "tenants#associate_tenant"

  resources :properties
  resources :users
  resources :property_owners, controller: 'users', user_designation: 'PropertyOwner'
  resources :tenants, controller: 'users', user_designation: 'Tenant'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property_owner.rb
class PropertyOwner < User
  has_many :properties, as: :utilizes
  
  def get_data_structure
    @data_struct = []
    get_properties
    units = []
    delinquencies = []
    issues = []
    @properties.each do |property|
      units = property.units
      units.each do |unit|
        if unit.delinquency != nil
          delinquencies.push(unit.delinquency)
        end
      end
      units.each do |unit|
        if unit.maintanence_services != nil
          issues.push(unit.maintanence_services)
        end
      end
      @data_struct.push(title: property.title, units: units, delinquencies: delinquencies, issues: issues)
      delinquencies = []
      issues = []
    end
    return @data_struct
  end
  
  def get_properties
    @properties = self.properties
  end
  
  def get_delinquencies
    @delinquencies = Delinquency.all
  end
  
end

app/models/workspace/property_owner.rb
class Workspace::PropertyOwner < ApplicationRecord
  belongs_to :user
end

app/controllers/property_owners_controller.rb
class PropertyOwnersController < ApplicationController
  before_action :set_property_owner, only: [:show, :edit, :update, :destroy]

  # GET /property_owners
  # GET /property_owners.json
  def index
    @property_owners = PropertyOwner.all
  end

  # GET /property_owners/1
  # GET /property_owners/1.json
  def show
    @tenants = Tenant.all.each { |tenant| tenant.units.empty? }
    @user = User.new
    @data = @property_owner.get_data_structure
    @property = Property.new
  end

  # GET /property_owners/new
  def new
    @property_owner = PropertyOwner.new
  end

  # GET /property_owners/1/edit
  def edit
  end

  # POST /property_owners
  # POST /property_owners.json
  def create
    @property_owner = PropertyOwner.new(property_owner_params)

    respond_to do |format|
      if @property_owner.save
        format.html { redirect_to @property_owner, notice: 'Property owner was successfully created.' }
        format.json { render :show, status: :created, location: @property_owner }
      else
        format.html { render :new }
        format.json { render json: @property_owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /property_owners/1
  # PATCH/PUT /property_owners/1.json
  def update
    respond_to do |format|
      if @property_owner.update(property_owner_params)
        format.html { redirect_to @property_owner, notice: 'Property owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @property_owner }
      else
        format.html { render :edit }
        format.json { render json: @property_owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /property_owners/1
  # DELETE /property_owners/1.json
  def destroy
    @property_owner.destroy
    respond_to do |format|
      format.html { redirect_to property_owners_url, notice: 'Property owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property_owner
      @property_owner = PropertyOwner.find(session[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_owner_params
      params.require(:property_owner).permit(:first_name, :last_name, :owner_address, :owner_phone, unitArrayToPass: [])
    end
end

app/helpers/property_owners_helper.rb
module PropertyOwnersHelper
end

app/views/property_owners/_form.html.erb
<%= form_for(property_owner) do |f| %>
  <% if property_owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property_owner.errors.count, "error") %> prohibited this property_owner from being saved:</h2>

      <ul>
      <% property_owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :owner_address %>
    <%= f.text_field :owner_address %>
  </div>

  <div class="field">
    <%= f.label :owner_phone %>
    <%= f.text_field :owner_phone %>
  </div>

  <div class="field">
    <%= f.label :number_of_properties %>
    <%= f.number_field :number_of_properties %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/property_owners/edit.html.erb
<h1>Editing Property Owner</h1>

<%= render 'form', property_owner: @property_owner %>

<%= link_to 'Show', @property_owner %> |
<%= link_to 'Back', property_owners_path %>

app/views/property_owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Property Owners</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Owner address</th>
      <th>Owner phone</th>
      <th>Number of properties</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @property_owners.each do |property_owner| %>
      <tr>
        <td><%= property_owner.first_name %></td>
        <td><%= property_owner.last_name %></td>
        <td><%= property_owner.owner_address %></td>
        <td><%= property_owner.owner_phone %></td>
        <td><%= property_owner.number_of_properties %></td>
        <td><%= link_to 'Show', property_owner %></td>
        <td><%= link_to 'Edit', edit_property_owner_path(property_owner) %></td>
        <td><%= link_to 'Destroy', property_owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property Owner', new_property_owner_path %>

app/views/property_owners/new.html.erb
<h1>New Property Owner</h1>

<%= render 'form', property_owner: @property_owner %>

<%= link_to 'Back', property_owners_path %>

app/views/property_owners/show.html.erb
<% content_for :title do %>
	<h1><%= @property_owner.first_name %> <%= @property_owner.last_name %></h2>
		<ul class="nav nav-pills">
		  <li class="active"><a data-toggle="tab" href="#secA">Home</a></li>
		  <li><a data-toggle="tab" href="#secB">Add New Property</a></li>
		</ul>
<% end %>

<style>
	.left-content
	{
		float: left;
		height: 300px;
		width: 75%;
		background-color: #eff5f5;
	}
	
	.right-content
	{
		float: right;
		height: 300px;
		width: 25%;
	}
	
	.boxes
	{
		float: left;
		width: 125px;
		height: 125px;
		background-color: #eff5f5;
		margin: 5px;
		line-height: 10;
		text-align: center;
	}
</style>

<div class="tab-content">
	<div id="secA" class="tab-pane fade in active">
		<% @data.each do |data| %>
		<div class="primary panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">
					<%= data[:title] %>
				</h3>
				<span>Delinquencies: </span><%= data[:delinquencies].count%>
				<span>Maintenance Issues: </span><%= data[:issues].count%>
			</div>
			<div class="panel-body">
				<div class="left-content">
					<% if data[:units].present? %>
						<%= label_tag 'Units' %>
						<%= select_tag 'Units',
								options_from_collection_for_select(data[:units],
								'address2',
								'address2'), class: 'form-control' %>
					<% end %>
				</div>
				<div class="right-content">
						<div class="boxes">
							<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">
								<i class="fa fa-usd fa-3x" aria-hidden="true"></i>
							</button>
						</div>
						<div class="boxes">
							<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#newTenant">
								<i class="fa fa-users fa-3x" aria-hidden="true"></i>
							</button>
						</div>
						<div class="boxes">
							<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">
								<i class="fa fa-wrench fa-3x" aria-hidden="true"></i>
							</button>
						</div>
						<div class="boxes">
							<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">
								<i class="fa fa-gavel fa-3x" aria-hidden="true"></i>
							</button>
						</div>
				</div>
				<div style="clear: both;"></div>
			</div>
		</div>
		<% end %>
	</div>
	
	<div id="secB" class="tabe-pane fade">
		<%= render "properties/new" %>
	</div>
</div>



<!-- Modals -->

<!-- Add new tenant modal -->
<div id="newTenant" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add New Tenant</h4>
      </div>
      <div class="modal-body">
        <%= render 'users/new' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>