config/routes.rb
Rails.application.routes.draw do
  get 'maintanence_service/index'

  get 'maintanence_service/new'

  post '/tenants/maintanence_services' => "maintanence_service#create"

  get 'maintanence_service/show'

  get 'workspace/index'

  root "sessions/sessions#index"
  namespace :sessions do
     resources :sessions
  end

  get "users" => "users#new", :as => "users"
  get "new_user_sign_up" => "users#new", :as => "new_user_sign_up"
  get "user_logged_out" => "sessions/sessions#destroy", :as => "user_logged_out"
  get "property_owners/PropertyOwner" => "property_owners#show", :as => "property_owner_workspace"
  get "tenants/Tenant" => "tenants#show", :as => "tenant_workspace"
  post "get_city" => "tenants#get_city"
  post "get_apts" => "tenants#get_apts"
  post "get_units" => "tenants#get_units"
  post "associate_tenant" => "tenants#associate_tenant"

  resources :properties
  resources :users
  resources :property_owners, controller: 'users', user_designation: 'PropertyOwner'
  resources :tenants, controller: 'users', user_designation: 'Tenant'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
   #belongs_to :utilizes, polymorphic: true
   has_and_belongs_to_many :users
   has_many :units
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show

  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    binding.pry
    # JSON.parse(params[:unitArrayToPass]) to get the units individually
    units = JSON.parse(params[:unitArrayToPass]) if params[:unitArrayToPass].present?
    @property = Property.new(property_params)
    if @property.save
      @property.users << User.find(session[:user_id])
      if units.present?
        units.each do |unit|
          Unit.create(address2: unit['unit'], 
            property_id: @property.id,
            rental_fee: unit['rent'],
            sq_ft: unit['area'],
            bdrms: unit['bdrms'],
            baths: unit['baths'],
            fl_lvl: unit['fllvl'])
        end
      end
      redirect_to property_owner_path(session[:user_type]), :notice => "New Property Added"
    else
      render "new"
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:title, :st_add, :city, :state, :zip, :user_id, :number_of_units)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(property) do |f| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :property_title %>
    <%= f.text_field :property_title %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :number_of_units %>
    <%= f.number_field :number_of_units %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/_new.html.erb
<style>
.left-container
{
	float: left;
	width: 48%;
}
.right-container
{
	float: right;
	width: 48%;
	height: 400px;
	overflow: scroll;
}
.width-control
{
	width: 100px;
}
.test {
	width: 100%;
}
.input-group .form-control {
	width: 50%;
}
.nopadding {
	padding: 0;
}
</style>
<script>
	function addNewUnit(event) {
		var unitArray = [];
		var unitNum;
		
		if(event.target.nodeName == "BUTTON" || event.target.nodeName == "I") {
			if(event.target.nodeName == "I") {
				unitArray = event.target.parentNode.id.split('-')
			}
			else {
				unitArray = event.target.id.split('-');
			}
		
			unitNum = unitArray[1];
			
			if((event.target.nodeName == "BUTTON" || event.target.nodeName == "I") && 
			document.getElementById('unit-icon-' + unitNum).className == 'fa fa-pencil') {
					document.getElementById("unitnumber" + unitNum).disabled = false;
					document.getElementById('unit-icon-' + unitNum).className = 'fa fa-check';
			}
			else {
					if((event.target.nodeName == "BUTTON" || event.target.nodeName == "I") && 
						document.getElementById('unit-icon-' + unitNum).className == 'fa fa-plus') {
						var newRowDiv = document.createElement('DIV');
						newRowDiv.className = 'row';
		
						var newDiv1 = createNewUnitTextInput('number', 3, (parseInt(unitNum)) + 1, 'Unit #');
						var newDiv2 = createNewUnitTextInput('rent', 6, (parseInt(unitNum)) + 1, '$');
						var newDiv3 = createNewUnitTextInput('area', 3, (parseInt(unitNum)) + 1, 'Area');
						
						newRowDiv.appendChild(newDiv1);
						newRowDiv.appendChild(newDiv2);
						newRowDiv.appendChild(newDiv3);
						
						var newRowDiv2 = document.createElement('DIV');
						newRowDiv2.className = 'row';
						
						var newDiv4 = createNewUnitTextInput('bdrms', 3, (parseInt(unitNum)) + 1, '# Bdrms');
						var newDiv5 = createNewUnitTextInput('baths', 6, (parseInt(unitNum)) + 1, '# Baths');
						var newDiv6 = createNewUnitTextInput('fllvl', 3, (parseInt(unitNum)) + 1, 'Floor Level');
						
						newRowDiv2.appendChild(newDiv4);
						newRowDiv2.appendChild(newDiv5);
						newRowDiv2.appendChild(newDiv6);
						
						var newRowDiv3 = document.createElement('DIV');
						newRowDiv3.className = 'row';
						
						var button = document.createElement('BUTTON');
						button.className = 'btn btn-default';
						button.type = 'button';
						button.id = "unit-" + (parseInt(unitNum) + 1);
		
						var icon = document.createElement('I');
						icon.className = 'fa fa-plus';
						icon.setAttribute('aria-hidden', 'true');
						icon.id = "unit-icon-" + (parseInt(unitNum) + 1);
		
						button.appendChild(icon);
						newRowDiv3.appendChild(button);
						var divContainer = document.getElementById('newUnitContainer');
						divContainer.appendChild(newRowDiv);
						divContainer.appendChild(newRowDiv2);
						divContainer.appendChild(newRowDiv3);
				
						document.getElementById("unitnumber" + (parseInt(unitNum) + 1)).focus();
					}
					document.getElementById('unit-icon-' + unitNum).className = 'fa fa-pencil';
					document.getElementById('unitnumber' + unitNum).disabled = true;
				}
		}
	}
	
	function createNewUnitTextInput(type, size, index, placeholder) {
		
		var newColDiv = document.createElement("DIV");
		newColDiv.className = 'col-md-' + size + ' nopadding';
		
		var newInput = document.createElement("INPUT");
		newInput.className = 'form-control'
		newInput.type = 'text';
		newInput.name = 'unit['+ type + 'Info]';
		newInput.id = 'unit' + type + index;
		newInput.placeholder = placeholder;
		
		newColDiv.appendChild(newInput);
		
		return newColDiv;
	}
	
	window.onload = function () {
		var addUnits = document.getElementById('unitsContainer')
		addUnits.addEventListener('click', addNewUnit, false);
	}
	
	function lockDownUnits() {
		var unitArray = [];
		
		var inputs = document.getElementsByTagName('INPUT');
		var unitInfo = {};
		
		for(var i=0; i<inputs.length; i++) {
			if(inputs[i].getAttribute('NAME') == "unit[numberInfo]")
				unitInfo["unit"] = inputs[i].value;
			if(inputs[i].getAttribute('NAME') == "unit[rentInfo]")
				unitInfo["rent"] = inputs[i].value;
			if(inputs[i].getAttribute('NAME') == "unit[areaInfo]")
				unitInfo["area"] = inputs[i].value;
			if(inputs[i].getAttribute('NAME') == "unit[bdrmsInfo]")
				unitInfo["bdrms"] = inputs[i].value;
			if(inputs[i].getAttribute('NAME') == "unit[bathsInfo]")
				unitInfo["baths"] = inputs[i].value;
			if(inputs[i].getAttribute('NAME') == "unit[fllvlInfo]")
				unitInfo["fllvl"] = inputs[i].value;
			
			if(Object.keys(unitInfo).length == 6) {
				unitArray.push(unitInfo);
				unitInfo = {};
			}
		}
		document.getElementById('unitArrayToPass').value = JSON.stringify(unitArray);
	}
</script>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Add New Property</h3>
	</div>
	<div class="panel-body">
		<div class="container left-container">
			<%= form_for @property do |f|%>
			<div class="row">
				<div class="col-md-12">
	        		<%= f.label :title %><br />
	        		<%= f.text_field :title, :class => 'form-control' %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
	        		<%= f.label :st_add, "Street Address" %><br />
	        		<%= f.text_field :st_add, :class => 'form-control' %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
	        		<%= f.label :city %><br />
	        		<%= f.text_field :city, :class => 'form-control' %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
	        		<%= f.label :state %><br />
	        		<%= f.text_field :state, :class => 'form-control' %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
	        		<%= f.label :zip %><br />
	        		<%= f.text_field :zip, :class => 'form-control' %>
				</div>
			</div>
		</div>
		<div id="unitsContainer" class="container right-container">
			<%= label_tag 'Units' %>
				<div id="newUnitContainer">

						<div class="row">
							<div class="col-md-3 nopadding">
								<input type="text" class="form-control" id="unitnumber1" name="unit[numberInfo]" placeholder="Unit#">
							</div>
							<div class="col-md-6 nopadding">
								<input type="text" class="form-control" id="unitrent1" name="unit[rentInfo]" placeholder="$">
							</div>
							<div class="col-md-3 nopadding">
								<input type="text" class="form-control" id="unitarea1" name="unit[areaInfo]" placeholder="Area">
							</div>
						</div>
						<div class="row">
							<div class="col-md-3 nopadding">
								<input type="text" class="form-control" id="unitbdrms1" name="unit[bdrmsInfo]" placeholder="# Bdrms">
							</div>
							<div class="col-md-3 nopadding">
								<input type="text" class="form-control" id="unitbaths1" name="unit[bathsInfo]" placeholder="# Baths">
							</div>
							<div class="col-md-6 nopadding">
								<input type="text" class="form-control" id="unitfllvl1" name="unit[fllvlInfo]" placeholder="Floor Level">
							</div>
						</div>
						<div class="row">
							<div class="col-md-6 nopadding">
						    
							</div>
							<div class="col-md-6 nopadding">
								<button id="unit-1" class="btn btn-default" type="button">
									<i id="unit-icon-1" class="fa fa-plus" aria-hidden="true"></i>
								</button>
							</div>
						</div>
					<!--
					<div class="col-md-12">
						<div class="input-group">
							<div class="container">
							<div class="row">
								<div class="col-md-4">
									<input type="text" class="form-control" id="unittext1" name="units" placeholder="Unit#">
								</div>
								<div class="col-md-4">
									<input type="text" class="form-control" placeholder="$">
								</div>
								<div class="col-md-4">
									<input type="text" class="form-control" placeholder="# Bdrms">
								</div>
							</div>
						</div>
							<span class="input-group-btn">
								<button id="unit-1" class="btn btn-default" type="button">
									<i id="unit-icon-1" class="fa fa-plus" aria-hidden="true"></i>
								</button>
							</span>
						</div>
					</div> -->
				</div>
				
		</div>
		<div class="row">
			<div class="col-md-4"></div><div class="col-md-4"></div>
			<div class="col-md-4">
				<button id="submitUnits" class="btn btn-default" type="button" onclick="lockDownUnits()">
					<i class="fa fa-plus" aria-hidden="true">Add Units</i>
				</button>
			</div>
			<%= hidden_field_tag "unitArrayToPass" %>
			<%= hidden_field_tag "user_id", value: session[:user_id]%>
		</div>
		<div class="row">
			<div class="col-md-12">
				<%= f.submit "Add New Property", :class => 'btn btn-default' %>
			</div>
		</div>
		<% end %>
		<div style="clear: both;"></div>
	</div>
</div>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Property title</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.title %></td>
        <td><%= property.st_add %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property title:</strong>
  <%= @property.property_title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Number of units:</strong>
  <%= @property.number_of_units %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>