config/routes.rb
Rails.application.routes.draw do
  get 'maintanence_service/index'

  get 'maintanence_service/new'

  post '/tenants/maintanence_services' => "maintanence_service#create"

  get 'maintanence_service/show'

  get 'workspace/index'

  root "sessions/sessions#index"
  namespace :sessions do
     resources :sessions
  end

  get "users" => "users#new", :as => "users"
  get "new_user_sign_up" => "users#new", :as => "new_user_sign_up"
  get "user_logged_out" => "sessions/sessions#destroy", :as => "user_logged_out"
  get "property_owners/PropertyOwner" => "property_owners#show", :as => "property_owner_workspace"
  get "tenants/Tenant" => "tenants#show", :as => "tenant_workspace"
  post "get_city" => "tenants#get_city"
  post "get_apts" => "tenants#get_apts"
  post "get_units" => "tenants#get_units"
  post "associate_tenant" => "tenants#associate_tenant"

  resources :properties
  resources :users
  resources :property_owners, controller: 'users', user_designation: 'PropertyOwner'
  resources :tenants, controller: 'users', user_designation: 'Tenant'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<style>
	.sub_nav
	{
		float: right;
	}
</style>
<div class="container">
<% if current_user %>
	<%= link_to "Log Out", user_logged_out_path, :class => "sub_nav" %>
<% else %>
	<%= link_to "Sign up", new_user_sign_up_path %>
<% end %>
</div>
<div style="clear: both"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Online Rental Payment Thingy</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navigation' %>
    <div class="container">
       <div class="jumbotron">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
          <header>
            <div class="page-header">
              <%= yield :title %>
            </div>
          </header>

       </div>

      <%= yield %>
    </div>
  </body>
</html>